USE better_reads_db;

INSERT INTO genre(name)
VALUES ('Action and adventure'),
    ('Alternate history'),
    ('Anthology'),
    ('Chick Lit'),
    ('Children''s'),
    ('Classic'),
    ('Comic book'),
    ('Coming-of-age'),
    ('Crime'),
    ('Drama'),
    ('Fairytale'),
    ('Fantasy'),
    ('Graphic novel'),
    ('Historical fiction'),
    ('Horror'),
    ('Mystery'),
    ('Paranormal romance'),
    ('Picture book'),
    ('Poetry'),
    ('Political thriller'),
    ('Romance'),
    ('Satire'),
    ('Science fiction'),
    ('Short story'),
    ('Suspense'),
    ('Thriller'),
    ('Western'),
    ('Young Adult'),
    ('Art/Architecture'),
    ('Autobiography'),
    ('Biography'),
    ('Business/Economics'),
    ('Crafts/Hobbies'),
    ('Cookbook'),
    ('Diary'),
    ('Health/Fitness'),
    ('History'),
    ('Humor'),
    ('Journal'),
    ('Math'),
    ('Philosophy'),
    ('Prayer'),
    ('Religion, Spirituality, New Age'),
    ('Review'),
    ('Science'),
    ('Self Help'),
    ('Sports and Leisure'),
    ('Travel'),
    ('True Crime'),
    ('Textbook');